# Generated by Django 4.0 on 2022-07-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0010_alter_annonces_img_annonce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonces',
            name='email_vendeur',
        ),
        migrations.RemoveField(
            model_name='annonces',
            name='lieu_produit',
        ),
        migrations.RemoveField(
            model_name='annonces',
            name='numero_vendeur',
        ),
        migrations.AlterField(
            model_name='annonces',
            name='nature',
            field=models.CharField(choices=[('occasion', 'occasion'), ('nouveau', 'nouveau')], default='occasion', max_length=50),
        ),
    ]
