# Generated by Django 4.0 on 2022-07-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0011_remove_annonces_email_vendeur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonces',
            name='lieu_produit',
            field=models.CharField(default='la livraion par rapport votre lieu', max_length=45),
        ),
    ]
