# Generated by Django 4.0 on 2022-07-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0012_annonces_lieu_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonces',
            name='lieu_produit',
            field=models.CharField(default='conakry', max_length=45),
        ),
    ]
