# Generated by Django 4.0 on 2022-07-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0013_alter_freelances_prix_jours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelances',
            name='nomfree',
        ),
        migrations.AlterField(
            model_name='clients',
            name='profil',
            field=models.ImageField(default='user.svg', error_messages={'non': 'donnez une photo de profile'}, upload_to='media/profil'),
        ),
        migrations.DeleteModel(
            name='concepts_freelance',
        ),
        migrations.DeleteModel(
            name='freelances',
        ),
    ]
