# Generated by Django 4.0 on 2022-01-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept_freelance',
            name='img_concept',
            field=models.ImageField(upload_to='media', verbose_name='image de la conception'),
        ),
    ]
