# Generated by Django 4.0 on 2022-07-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0010_commandes_alls_date_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandes_alls',
            name='qt',
            field=models.IntegerField(default=1),
        ),
    ]
